# Generated by Django 6.1.1 on 2026-09-30 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_category_alter_recipe_cover'),
        ('recipes', '0002_recipe_tags'),
    ]

    operations = [
    ]
